repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: python-unit-tests
        name: seegras unit tests
        entry: pytest -k "not _integration" tests
        pass_filenames: false
        types: [python]
        language: system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
