model:
  model_name: resnet18
  pretrained: true
  n_classes: 1

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 20
  optimizer: Adam
  scheduler: step_lr
  loss_function: BinaryCrossEntropy
  step_size: 5
  shuffle: true
