model:
  model_name: resnet18
  pretrained: true
  n_classes: 1
  trainable: true

training:
  batch_size: 4
  learning_rate: 0.001
  num_epochs: 20
  optimizer: Adam
  scheduler: step_lr
  loss_function: BCEWithLogitsLoss
  step_size: 5
  shuffle: true
